version: '3'

services:
  vyos1:
    build: ./vyos/vyos1
    privileged: true
    container_name: vyos1
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/net/tun
    volumes:
      - "/lib/modules:/lib/modules:ro" 
      - "./vyos/vyos1/config.init:/config.init"
      - "./config:/opt/vyatta/etc/config"
    entrypoint:
      - /sbin/init

  vyos2:
    build: ./vyos/vyos1
    privileged: true
    container_name: vyos2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/net/tun
    volumes:
      - "/lib/modules:/lib/modules:ro" 
      - "./vyos/vyos2/config.init:/config.init"
      - "./config:/opt/vyatta/etc/config"
    entrypoint:
      - /sbin/init

  mail-server:
    build: ./mail-server
    privileged: true
    container_name: mail-server
    cap_add:
      - NET_ADMIN
    environment:
      - ADMIN_USERNAME=root
      - ADMIN_PASSWD=password
      - DOMAINE_NAME=localhost
      - USERS=user1:pass1,user2:pass2
    volumes:
      - "/data/ysql:/varlib/mysql"
      - "/data/vmail/:/var/vmail"
      - "/data/log:/var/log"
    ports:
      - "25:25"
      - "80:80"
      - "110:110"
      - "143:143"
      - "465:465"
      - "993:993"
      - "995:995"
    entrypoint:
      - /sbin/init
    
  mysql-server:
    build: ./mysql-server
    privileged: true
    cap_add:
      - NET_ADMIN     
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=toor

  adminer:
    image: adminer
    container_name : adminer
    ports:
      - "8080:8080"

  client:
    build: ./client
    container_name: client
    privileged: true
    cap_add:
      - NET_ADMIN
    entrypoint:
      - /sbin/init
